name: Install
on:
  workflow_call:
env:
  NODE_VERSION: 18.x
  PNPM_VERSION: 8.13.1
jobs:
  install:
    runs-on: ubuntu-latest
    outputs:
      pnpm-cache-key: ${{ steps.cache.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/pnpm
          key: ${{ runner.os }}-pnpm-${{ hashFiles('pnpm-lock.yaml') }}
      - name: Install dependencies
        run: pnpm install
