name: Lint
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_call:
jobs:
  lint:
    needs: lint_install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Lint & format
        run: pnpm run ci
