name: Lint
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_call:
jobs:
  install:
    uses: ./.github/workflows/install.yml`
  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Lint & format
        run: pnpm ci
