name: Release
on:
  push:
    tags: 
      - 'v*'
jobs:
  release_build:
    uses: ./.github/workflows/build.yml
  release:
    needs: release_build
    runs-on: ubuntu-latest
    steps:
      - name: Exit if not on master branch
        if: endsWith(github.ref, 'master') == false
        run: exit 0
      - name: Create Release 
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: 'dist/*'
      - name: Publish to NPM
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}