name: Test
on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: true
      - name: Test
        run: pnpm test
